server:
  port: 8080

spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1908?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka
